"""added version table

Revision ID: 030cbfdb3bcf
Revises: fbb6df3a3f18
Create Date: 2025-07-26 16:34:35.536532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030cbfdb3bcf'
down_revision: Union[str, Sequence[str], None] = 'fbb6df3a3f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('release_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('release_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version', schema='public')
    # ### end Alembic commands ###
