"""added orchestrator table app fields

Revision ID: 31f392f4e451
Revises: 63a705fda90d
Create Date: 2025-09-20 15:04:09.874165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31f392f4e451'
down_revision: Union[str, Sequence[str], None] = '63a705fda90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orchestrator', 
        sa.Column('publish_as_app', sa.Boolean(), server_default='true'),
        schema='agents'
    )
    op.add_column('orchestrator', 
        sa.Column('app_type', sa.String(length=50), server_default='Productivity'),
        schema='agents'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orchestrator', 'publish_as_app', schema='agents')
    op.drop_column('orchestrator', 'app_type', schema='agents')
    # ### end Alembic commands ###
