"""added Agent table

Revision ID: 50828418ad89
Revises: 71f30ce938a2
Create Date: 2025-07-26 16:37:21.375221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50828418ad89'
down_revision: Union[str, Sequence[str], None] = '71f30ce938a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['config.api_key.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='agents'
    )
    op.create_table('agent_mcp_server',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['config.mcp_server.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('agent_id', 'mcp_server_id'),
    schema='agents'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_mcp_server', schema='agents')
    op.drop_table('agent', schema='agents')
    # ### end Alembic commands ###
