"""Added new columns to agent and mcpServer tables

Revision ID: 63a705fda90d
Revises: 69dd3c825cbe
Create Date: 2025-09-13 23:21:19.588822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a705fda90d'
down_revision: Union[str, Sequence[str], None] = '69dd3c825cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', 
        sa.Column('transport', sa.String(length=50), server_default='stdio'),
        schema='config'
    )
    op.add_column('mcp_server', 
        sa.Column('mode', sa.String(length=50), server_default='autonomous'),
        schema='config'
    )
    op.add_column('agent', 
        sa.Column('publish_as_app', sa.Boolean(), server_default='false'),
        schema='agents'
    )
    op.add_column('agent', 
        sa.Column('app_type', sa.String(length=50), server_default='Productivity'),
        schema='agents'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server', 'transport', schema='config')
    op.drop_column('mcp_server', 'mode', schema='config')
    op.drop_column('agent', 'publish_as_app', schema='agents')
    op.drop_column('agent', 'app_type', schema='agents')
    # ### end Alembic commands ###
