"""added Orchestrator table

Revision ID: 69dd3c825cbe
Revises: 50828418ad89
Create Date: 2025-07-26 16:39:13.571184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69dd3c825cbe'
down_revision: Union[str, Sequence[str], None] = '50828418ad89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestrator',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['config.api_key.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='agents'
    )
    op.create_table('orchestrator_sub_agent',
    sa.Column('orchestrator_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orchestrator_id'], ['agents.orchestrator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('orchestrator_id', 'agent_id'),
    schema='agents'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orchestrator_sub_agent', schema='agents')
    op.drop_table('orchestrator', schema='agents')
    # ### end Alembic commands ###
