"""initial

Revision ID: fbb6df3a3f18
Revises: 
Create Date: 2025-07-26 16:29:16.976250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb6df3a3f18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS config")
    op.execute("CREATE SCHEMA IF NOT EXISTS agents")
    #op.execute("CREATE SCHEMA IF NOT EXISTS runtime")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS config")
    op.execute("DROP SCHEMA IF EXISTS agents")
    #op.execute("DROP SCHEMA IF EXISTS runtime")
    # ### end Alembic commands ###
